name: 'Sync repository'
on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Syncing repository
        run: |
          gh repo sync $REPOSITORY -b main
          gh repo sync $REPOSITORY -b develop
          git pull
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
